OCADDRESS: "https://ocp.dc1.example.com:443"
OCUSER: "system:admin"
BACKUPDIR: "/backupOCP/{{ansible_date_time.date}}/objects/{{ ansible_hostname }}"
objects:
  - rolebindings
  - serviceaccounts
  - secrets
  - imagestreamtags
  - cm
  - egressnetworkpolicies
  - rolebindingrestrictions
  - limitranges
  - resourcequotas
  - dc
  - ds
  - pv
  - pvc
  - templates
  - cronjobs
  - statefulsets
  - hpa
  - deployments
  - replicasets
  - poddisruptionbudget
  - endpoints
  - oauthclient
  - route
  - rc
  - is
  - networkpolicies
